### PR TITLE
[#685] feat: buttons leaderboard

### PR DESCRIPTION
**Pull request by chedieck**
Related to #685

Description
---
Implements #685:

image

Test plan
---
After loading the branch, reset the cache with `yarn docker cmr` and check if the leaderboard appears normally.

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
- Can we have 'Total Revenue' match the charts in that they're using the user's selected fiat currency to measure it? This would be the daily $ summed up (same as if they had manually looked at the revenue chart and added up the $ from each day). Right now I'm not even sure what number it's using because there's no '$' symbol and the decimals should be limited to 2.
- Set decimal rounding to 2.
- On the dev account, 'Foo XEC' has only 1 transaction but the leaderboard shows 2 payments.

**Comment by Klakurka** [comment]
I forgot to reset the cache so I'll do that when I can test next.

**Comment by chedieck** [comment]
> * Can we have 'Total Revenue' match the charts in that they're using the user's selected fiat currency to measure it? This would be the daily $ summed up (same as if they had manually looked at the revenue chart and added up the $ from each day). Right now I'm not even sure what number it's using because there's no '$' symbol and the decimals should be limited to 2.

> Set decimal rounding to 2.

I changed it so it uses the same formatting function as the other places in the same page: it uses 2 digits of precision unless the quantity is very small, in which case it just shows the first significant digit.
 

>   On the dev account, 'Foo XEC' has only 1 transaction but the leaderboard shows 2 payments.

I couldn't reproduce that: in my leaderboard, as seen in the printscreen, `Foo XEC` shows as having only one payment.

**Comment by chedieck** [comment]
Observation:

image


Here we can see that the total payments according to the top right chart is 39, but adding up the payments from the leaderboard gives us 40.

This happens because two buttons share the same address, so this single payment appears twice in the leaderboard: as the one payment for **"Foo XEC"** and for **"Paybutton XEC & Coindance BCH"**

**Review by Klakurka — CHANGES_REQUESTED** [review]
Other changes look good but I still have this issue:

image

(total payments is wrong somehow)

**Review by Klakurka — APPROVED** [review]
Looks like it's probably #695 which we can do next.

**Pull request merged**
