### PR TITLE
refactor: remove alternative address routes

### PR DESCRIPTION
**Pull request by chedieck**
**Description:**
Remove alternative routes.

**Test plan:**
On master, running:
```
curl http://localhost:3000/balance/[address]
```
or
```
curl http://localhost:3000/address/balance/[address]
```
have the same effect. The same applies to:
```
curl http://localhost:3000/transactions/[address]
curl http://localhost:3000/address/transactions/[address]
```

Now, only the first ones should work.

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
On this branch when I try to access /transactions/xxx for an address that we don't have yet, it just returns this instead of returning the latest data:

`{"statusCode":404,"message":"No address found."}`

Is this what you're seeing? If that's the case then it'll break the client setup unless there another way to get the data.

**Comment by Klakurka** [comment]
Also I know it might be annoying to swap them but was there reason you chose the shorter URLs over the longer ones that included /address/ ? I think the client is expecting /address/ and also do you think this might be more clear to use the longer URL as the project grows and new pages are added?

**Comment by chedieck** [comment]
> Also I know it might be annoying to swap them but was there reason you chose the shorter URLs over the longer ones that included /address/ ? I think the client is expecting /address/ and also do you think this might be more clear to use the longer URL as the project grows and new pages are added?

I chose the short ones merely for convenience, I will swap them.

**Comment by Klakurka** [comment]
I just triple checked and the client uses the following:

- https://api.paybutton.org/address/transactions/[address]
- https://api.paybutton.org/address/balance/[address]

**Comment by chedieck** [comment]
Update:
I left the route rewriting out and simply moved the files into the `api/address` directory, so that now the URLs that are expected are the ones that start with `address`.

**Review by Klakurka — APPROVED** [review]

**Review by ScottMcDermid — APPROVED** [review]
Code looks good

**Pull request merged**
