### PR TITLE
feat: frontend basic components and initial structure

### PR DESCRIPTION
**Pull request by alcipir**
- Basic CSS structure using a very simple lib: simplecss.org
- Basic components: Layout, Page, Sidebar, MenuItem
- Took off the old form/addpaybuttons components from index, as I will change them soon.
- **It's just a starting point**, we will and can change some of this structure in the near future.
- Storybook to be added in another PR.
- Add Button frontend functionality to be add in another PR.
- Every component has a css module inside its folder. 
- There is a global css file to customize style from simplecss.org.

Open to suggestions.

### CODE REVIEW

**Review by johnkuney — APPROVED** [review]
Yeah looks like a good library choice and great starting point

**Comment by alcipir** [comment]
Thanks, @johnkuney. This will be ready for review in a few hours as I want to add css variables for the colors used and other tiny issues that I found. 

@chedieck I will ask for your review as well, since we both might have to tackle more frontend stuff in the near term.

**Comment by alcipir** [comment]
Added CSS variables and tiny modifications for more reusable CSS code. Ready for review.

**Review by Gattaca1 — APPROVED** [review]
Looks like a good starting point to me

**Pull request merged**
