### PR TITLE
[Issue #182] feat: in and out transactions

### PR DESCRIPTION
**Pull request by chedieck**
**Descripition:**
Solves #182 . An outward transaction from some address will have a negative amount.

**Test plan:**
Let `bchaddr` be some bitcoin cash address with IN and OUT transactions. Then:
- Create a Paybutton with the address `bchaddr`, 
- Run `curl -X GET http://localhost:3000/api/transactions/sync/bchaddr` to save the transactions in the database,
- Run `curl -X GET http://localhost:3000/api/transactions/bchaddr | jq` and  see if the transactions are correctly displayed.

Depends on:
- [x] #176 
- [x] #178

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
Actually I no longer see results in `http://localhost:3000/button/1` anymore after a sync.

**Comment by Klakurka** [comment]
Needs conflicts resolved.

**Comment by Klakurka** [comment]
I get `{"statusCode":500,"message":"No address found."}`

**Comment by chedieck** [comment]
> I get `{"statusCode":500,"message":"No address found."}`

Can you tell me which address were you trying?

**Comment by Klakurka** [comment]
`http://localhost:3000/api/transactions/bitcoincash:qzqh7ej2vz26a9xaxq7capzfwgxt5gem9g8rvfxc5t`

**Comment by chedieck** [comment]
> `http://localhost:3000/api/transactions/bitcoincash:qzqh7ej2vz26a9xaxq7capzfwgxt5gem9g8rvfxc5t`

My bad, forgot to say you have to first create a paybutton with that address (using the frontend). Fixed the PR description.

**Comment by Klakurka** [comment]
The hash is the base 64 hash still. Do we need to rebase for that to use base 16?

**Comment by chedieck** [comment]
> The hash is the base 64 hash still. Do we need to rebase for that to use base 16?

Fixed.

**Review by Klakurka — APPROVED** [review]

**Review by Gattaca1 — APPROVED** [review]

**Pull request merged**
