### PR TITLE
[Issue 141] feat: optional domain for api/app and base path configuration

### PR DESCRIPTION
**Pull request by alcipir**
Description: Related to #141 (and will help #79), also enables changing api base path if needed (as in api.paybutton.org without subfolders for example).

Proper local environment variables available on `.env.development`

Test Plan: `make dev` should work as usual, adding different environment values on `.env` should break the website/change accordingly (e.g. if you are running on a local server or just changing `hosts` file to map to another domain. Or different subfolders.)

### CODE REVIEW

**Review by ScottMcDermid — CHANGES_REQUESTED** [review]
I'm getting infinite redirects, when I attempt to load `localhost:3000`. If I pause the redirect at the right time, I get an error message.

**Comment by ScottMcDermid** [comment]
> I'm getting infinite redirects, when I attempt to load `localhost:3000`. If I pause the redirect at the right time, I get an error message.

Wanted to clarify that I was using the proper local environment variables available on `.env.development`

**Review by Klakurka — CHANGES_REQUESTED** [review]
Let's put paybutton.org in here since we don't really want to be advertising the .io domains.

**Comment by ScottMcDermid** [comment]
> Thanks @ScottMcDermid, do you mind adding you to review these deployment related PRs?

Ya, for sure.

> I was going to ask if you ran docker rm -f $(docker ps -aq), but cache issues should not be happening anymore with the recent Dockerfile modification, so I will investigate.

Tried it anyways, and had the same result. The `master` branch does not have the same redirecting loop for me.

**Comment by Klakurka** [comment]
Tests failing.

**Review by ScottMcDermid — APPROVED** [review]

**Pull request merged**
