### PR TITLE
fix: throw if price request fails

### PR DESCRIPTION
**Pull request by chedieck**
Description
---
If the API call to coin.dance fails, we will get an error now.

Test plan
---
Change the `"priceAPIURL"` variable in `paybutton-config.json` to an invalid one. 

In master, eventually this would appear as something like:

```
2|next  | 2024-02-12T15:21:40: When syncing missing addresses for address ecash:qpun29ufvq56sksyxztwe7ntn0h60rah856a972rx6 encountered error: Error: Prices not found.
2|next  | 2024-02-12T15:21:40:     at fetchPricesForNetworkAndTimestamp (webpack-internal:///./services/priceService.ts:244:11)
2|next  | 2024-02-12T15:21:40:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2|next  | 2024-02-12T15:21:40:     at async fetchPricesForNetworkAndTimestamp (webpack-internal:///./services/priceService.ts:241:14)
2|next  | 2024-02-12T15:21:40:     at async fetchPricesForNetworkAndTimestamp (webpack-internal:///./services/priceService.ts:241:14)
2|next  | 2024-02-12T15:21:40:     at async connectTransactionToPrices (webpack-internal:///./services/transactionService.ts:228:21)
2|next  | 2024-02-12T15:21:40:     at async eval (webpack-internal:///./services/transactionService.ts:276:7)
2|next  | 2024-02-12T15:21:40:     at async Proxy._transactionWithCallback (/home/node/src/node_modules/@prisma/client/runtime/library.js:179:9413)
2|next  | 2024-02-12T15:21:40:     at async connectTransactionsListToPrices (webpack-internal:///./services/transactionService.ts:266:3)
2|next  | 2024-02-12T15:21:40:     at async createManyTransactions (webpack-internal:///./services/transactionService.ts:308:9)
2|next  | 2024-02-12T15:21:40:     at async ChronikBlockchainClient.syncTransactionsForAddress (webpack-internal:///./services/chronikService.ts:326:37)
2|next  | 2024-02-12T15:21:40:     at async syncTransactionsForAddress (webpack-internal:///./services/blockchainService.ts:66:20)
2|next  | 2024-02-12T15:21:40:     at async syncAddresses (webpack-internal:///./services/transactionService.ts:332:24)
2|next  | 2024-02-12T15:21:40:     at async ChronikBlockchainClient.syncMissedTransactions (webpack-internal:///./services/chronikService.ts:510:11)
```

While in this PR the error should be something more clear like:
```
2|next  | 2024-02-12T15:13:54: When syncing missing addresses for address ecash:qpxqkww4xu0xntchadw4zhetxhavx9l7lqxv9wzu3z encountered error: Error: getaddrinfo ENOTFOUND coin.dancse
2|next  | 2024-02-12T15:13:54:     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
```

### CODE REVIEW

**Comment by Klakurka** [comment]
I'm not sure how best to test this.

**Comment by chedieck** [comment]
> I'm not sure how best to test this.

Added a test plan.

**Review by Klakurka — CHANGES_REQUESTED** [review]
I see this in the branch:

image

**Review by Klakurka — CHANGES_REQUESTED** [review]
I'm not seeing the error catch, just this:

image

**Review by Klakurka — APPROVED** [review]

**Pull request merged**
