### PR TITLE
Feature: Add paybutton `name`, `uuid` and `buttonData` fields — Create parsers

### PR DESCRIPTION
**Pull request by chedieck**
Description:
Part of #33: Creates functions to parse the new fields, plus their unittests. In this PR, the fields still don't exist. Thus, the validators created are are still not being used.

Test plan:
All tests should pass.

### CODE REVIEW

**Comment by Klakurka** [comment]
I was just thinking about this one today.

We are going to be supporting BIP 70 which already supports arbitrary data like what might go into `buttonData`. So is this fine? We don't want to be maintaining two separate fields for arbitrary data after BIP 70 is out so I assume we'll reuse this one?

**Review by Klakurka — COMMENTED** [review]
The task was to add a client ID (to identify the app/website) and another for arbitrary data but there's 3 new ones here.

What's `userId` and `name` for?

**Comment by Klakurka** [comment]
Actually maybe we can have there be a url/app field that is automatically populated with the url the button is on.

Then, we could also allow them to enter a button name + ButtonData.

Thoughts?

**Comment by chedieck** [comment]
> I was just thinking about this one today.
> 
> We are going to be supporting BIP 70 which already supports arbitrary data like what might go into `buttonData`. So is this fine? We don't want to be maintaining two separate fields for arbitrary data after BIP 70 is out so I assume we'll reuse this one?

When we go on supporting BIP 70, won't this arbitrary data used by the paybutton need to be saved on the database?

> The task was to add a client ID (to identify the app/website) and another for arbitrary data but there's 3 new ones here.
> 
> What's `userId` and `name` for?

I had understand, from the issue description, that the user would input a unique name (for the user + server) for the paybutton, that's why I implemented the `name` field.
`userId` is not a field of the paybutton, there is already a field called `providerUserId`, which is the `userId` of the user who created the paybutton, and now there is the `uuid` field, which is just a universal unique identifier that is generated automatically when creating the paybutton:
image


> Actually maybe we can have there be a url/app field that is automatically populated with the url the button is on.
> 
> Then, we could also allow them to enter a button name + ButtonData.
> 
> Thoughts?

Can we know this URL without the user inputting it, in order to automatically populate this field? Maybe the paybutton would have to be used at least once in order to do that

**Review by Klakurka — APPROVED** [review]
Ok nevermind I thought this was about the API to the buttons which it's not.

That looks good to me.

**Review by Gattaca1 — APPROVED** [review]
looks good

**Pull request merged**
