### PR TITLE
[Issue #264] feat: update payments cache

### PR DESCRIPTION
**Pull request by chedieck**
Depends on
---
- [x] #488

Description
---
Now the cache updates when a new address is added or when a new transactions comes. This is updating the transaction even when it's confirmed, I'll open an issue to deal with this (so it is only added after confirmation) and address is after #478, since it changes this logic.

Test plan
---
Add an address, preferably one of yours. See if the payments in the dashboard correctly reflect this addition. Send some XEC to that address, see if that also is correctly updated. Finally, delete the address, see if it went away.

Remarks
---
Removed redis cache persistence. The db is reset with the containers, so no point in persisting the cache if we don't do it with the DB.

### CODE REVIEW

**Comment by Klakurka** [comment]
Checks failing.

**Comment by chedieck** [comment]
> Checks failing.

Should be fixed now

**Comment by Klakurka** [comment]
Conflicts.

**Review by Klakurka — CHANGES_REQUESTED** [review]
Both the dashboard and the transactions page don't show any txs for the address that I add. I get this in the logs:

image

**Comment by chedieck** [comment]
> Both the dashboard and the transactions page don't show any txs for the address that I add. I get this in the logs:
> 
> image

When do you get that, exactly? after adding the address?

**Comment by Klakurka** [comment]
Yeah... Might be at other times too. I'll have to check.

**Comment by Klakurka** [comment]
image

I get this after adding a new button with txs, then accessing the dashboard.

**Comment by chedieck** [comment]
> I get this after adding a new button with txs, then accessing the dashboard.

@Klakurka should be fixed now. It's possible that you have to delete `redis/dump.rdb` (delete it if it exists) because this PR changes the redis behavior to not persist anything.

**Review by Klakurka — CHANGES_REQUESTED** [review]
I don't get any errors now but adding a new button doesn't seem to pull in the txs for it.

image

**Review by Klakurka — APPROVED** [review]

**Pull request merged**
