### PR TITLE
[Issue #160] feat: add docs link to navbar

### PR DESCRIPTION
**Pull request by johnkuney**
Adding a link to docs.paybutton.org in the navbar

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
Nit: I think it's a different (darker) grey than the twitter and telegram icons are (light mode).

Also tooltips might be nice on these buttons.

**Comment by johnkuney** [comment]
ah good catch yeah should be slightly off-black, and yeah good call added some tooltips

**Comment by Klakurka** [comment]
The dark mode toggle is also using the darker colour if you think they should all be the same.

**Review by Klakurka — APPROVED** [review]
I think it's good as it is.

**Pull request merged**
