### PR TITLE
[Issue #88] feat: automatic detect payments

### PR DESCRIPTION
**Pull request by chedieck**
**Description:**
Solves #88. Creates #346.
Addresses are now subscribed when they are added, such that if a new transactions appears on any address, it is automatically added to the DB.

**Test plan:**
After building, create a paybutton with of **your** addresses. Then, using [Electrum ABC](https://github.com/Bitcoin-ABC/ElectrumABC) or any other XEC wallet, transfer some small quantity to that address. After the transaction is confirmed, it should appear on  the button detail. Same thing with Bitcoin Cash.

Depends on:
- [x] #342

### CODE REVIEW

**Review by ScottMcDermid — APPROVED** [review]
Code looks good. Transactions are populated as expected.

**Review by Klakurka — COMMENTED** [review]
It doesn't work for me for some reason (new txs not showing up) but I'll maybe try again later if we don't have any other ideas.

**Comment by Klakurka** [comment]
Ok it seems to not work on particular addresses... maybe just addresses that have been used already?

**Comment by Gattaca1** [comment]
Works for me. 

It would be nice if there was some sort of user feedback to let a user know that its syncing. Initially I thought it didn't work but I was just being impatient

**Pull request merged**
