### PR TITLE
[Issue #549] feat: configurable db credentials

### PR DESCRIPTION
**Pull request by chedieck**
Related to #549 

Description
---
Database credentials are fully configurable using env files.

Test plan
---
Check the defaults in `.env`. These can be changed or overridden on `.env.local`. Resetting the containers should always work regardless, and the changed settings can be tested by entering the DB container (`yarn docker dbs`)  and running e.g.:

```
mariadb -u <main_db_user> -p<main_db_password> -D <main_db_name>
```
or for supertokens credentials:
```
mariadb -u <supertokens_db_user> -p<supertokens_db_password> -D supertokens
```
...substituing the `<variables>` above for the same value set on the `.env` or `.env.local` files.

### CODE REVIEW

**Comment by ScottMcDermid** [comment]
Attempting to run `yarn docker dbs` gives me an error:

```
❯ yarn docker dbs
yarn run v1.22.19
$ ./scripts/docker-exec-shortcuts.sh dbs
./scripts/docker-exec-shortcuts.sh: line 11: .: .env: file not found
```

**Review by ScottMcDermid — CHANGES_REQUESTED** [review]
`yarn docker dbs` gives me an error:
```
❯ yarn docker dbs
yarn run v1.22.19
$ ./scripts/docker-exec-shortcuts.sh dbs
./scripts/docker-exec-shortcuts.sh: line 11: .: .env: file not found
```

**Comment by chedieck** [comment]
> 

Do you have a `.env` file? Because that's a commited file, so it should be present in the repo. `yarn docker dbs` works normally for me

**Comment by ScottMcDermid** [comment]
I have an `.env` and `.env.local` file. Using `yarn docker dbs` on `master` works for me, but not this branch.

**Comment by ScottMcDermid** [comment]
I can work around the convenient script, and call the command directly.
`doc exec db mariadb -u paybutton-user -p paybutton`

This allows me to connect with the updated username/password

**Comment by ScottMcDermid** [comment]
I found something odd when I tried running parts of the `docker-exec-shortcuts.sh`

```
$ . .env
.: no such file or directory: .env
```

versus:

```
. ./.env
```

which works.

Also, David tried running both of these, and encountered no errors.

**Comment by ScottMcDermid** [comment]
Ok.. Learned something new:

https://superuser.com/a/1499030

Seems to be a specific bash feature. I use zsh, which requires a path or else it searches `$PATH`.

Can we add the relative path in order to make this compatible with any shell?

```
. ./.env
. ./.env.local
```

**Comment by chedieck** [comment]
> Ok.. Learned something new:
> 
> https://superuser.com/a/1499030

Very cool, didn't know that either. Fixed.

**Review by ScottMcDermid — APPROVED** [review]

**Pull request merged**
