### PR TITLE
Fixed reseeding prisma issue

### LINKED ISSUE #126: Prisma failing when running seeds on a container that ran it previously
$ dotenv -e .env.development -- prisma db seed
Environment variables loaded from .env
Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
PrismaClientKnownRequestError: 
Invalid `prisma.chain.createMany()` invocation in
/app/src/prisma/seed.ts:6:22

  3 const prisma = new PrismaClient()
  4 
  5 async function main (): Promise<void> {
→ 6   await prisma.chain.createMany(
  Unique constraint failed on the constraint: `Chain_slug_key`
    at Object.request (/app/src/node_modules/@prisma/client/runtime/index.js:45405:15)
    at PrismaClient._request (/app/src/node_modules/@prisma/client/runtime/index.js:46301:18)
    at main (/app/src/prisma/seed.ts:6:3) {
  code: 'P2002',
  clientVersion: '3.14.0',
  meta: { target: 'Chain_slug_key' }
}

### PR DESCRIPTION
**Pull request by chedieck**
Description:
Fixes #126 
Sometimes, e.g when restarting the docker container, prisma would try to seed the database; but the database already contained the entries. Then the container would fail and be constantly restarting.
This PR fixes that

Test Plan:
Just manually run `yarn docker prisma db seed` twice and it shouldn't fail (the seeding is now only actually done if there are no entries in the database).

### CODE REVIEW

**Comment by Gattaca1** [comment]
I think `yarn docker prisma seed` might be the wrong command

**Comment by chedieck** [comment]
> I think `yarn docker prisma seed` might be the wrong command

Indeed, fixed in the description.

**Review by Klakurka — APPROVED** [review]

**Comment by Gattaca1** [comment]
Can you pull master into this? i'm getting quite a few build errors

**Comment by chedieck** [comment]
> Can you pull master into this? i'm getting quite a few build errors

Done

**Comment by Gattaca1** [comment]
To fix an issue, it would be good if we could recreate it. Attempting to run the seed file twice on master branch just throws an `Invalid invocation` error on `prisma.chain.createMany()`.

My attempt at recreating the reseeding prisma issue was to run `docker exec paybutton-dev prisma db seed` on master

**Review by Gattaca1 — APPROVED** [review]

**Pull request merged**
