### PR TITLE
[Issue #395] feat: remodel address to wallet on wallet card

### PR DESCRIPTION
**Pull request by chedieck**
Description:
Shows the paybuttons that belongs to a wallet by inferring them from the wallet addresses.

Test plan:
Go on to create a new wallet, select some address to it. See if all wallets now are correctly inferring their paybuttons.

Remarks:
- Now, editing a wallet will produce unexpected results. This will be later addressed in another PR.

Depends on:
- [x] #398

### CODE REVIEW

**Comment by Klakurka** [comment]
I'm not sure how to test this as they're all greyed out.

**Comment by chedieck** [comment]
> I'm not sure how to test this as they're all greyed out.
You can add new ones or reset the database, which should bring it to a state where not all will be greyed out

**Comment by Klakurka** [comment]
Maybe we should indicate that an address is in use in XYZ wallet?

**Review by ScottMcDermid — APPROVED** [review]
Looks good

**Comment by Klakurka** [comment]
@chedieck Actually can you explain again why all of the addresses there are unavailable to be used in the new wallet I was trying to make?

**Review by Klakurka — APPROVED** [review]
We're going to allow empty wallets.

**Pull request merged**
