### PR TITLE
[Issue 132] Add Github Actions to Run Lint, Unit and Integration tests on every push to master

### PR DESCRIPTION
**Pull request by alcipir**
Description: #132

Test Plan: https://github.com/PayButton/paybutton-server/tree/ci/issue/132 should show badge failing on README, clicking on it should show the latest action run for this workflow.

### CODE REVIEW

**Comment by Gattaca1** [comment]
> Description: #132
> 
> Test Plan: https://github.com/PayButton/paybutton-server/tree/ci/issue/132 should show badge failing on README, clicking on it should show the latest action run for this workflow.

clicking on the badge just links to the svg image of the badge

**Review by Klakurka — APPROVED** [review]
Cool

**Review by Gattaca1 — CHANGES_REQUESTED** [review]
The code itself looks good, however..

Having a badge that always shows failing removes the badges usefulness. I would prefer it to be an indicator that something bad happened that needs a fix. 

With that in mind, lets get the unlinted files fixed before merging this branch; there are 15 judging by the error messages

`

- paybutton-server/components/AddPayButtonForm.tsx
- paybutton-server/components/Paybutton/index.tsx
- paybutton-server/jest.config.js
- paybutton-server/next-env.d.ts
- paybutton-server/next.config.js
- paybutton-server/pages/_app.tsx
- paybutton-server/pages/api/address/transactions/[address].ts
- paybutton-server/pages/api/graphql.ts
- paybutton-server/pages/api/resolvers/index.ts
- paybutton-server/pages/api/schemas/index.ts
- paybutton-server/pages/auth/[[...path]].tsx
- paybutton-server/pages/index.tsx
- paybutton-server/services/bchdService.ts
- paybutton-server/tests/setup.js
- paybutton-server/types/index.ts`

**Comment by Klakurka** [comment]
Ya better to fix the failures now if we can.

**Comment by chedieck** [comment]
> Can we just remove the lint check for now instead of spending time fixing those issues, due to #127? What do you think?
> 
> Personally, I find it hard to test Github Actions locally, I would prefer to have something in place, like the unit and integration tests, in order to [keep master green as much as possible](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/CONTRIBUTING.md#bitcoin-abc-development-philosophy). I would like some guidance for this pull request with that in mind. @chedieck

I agree with removing the lint check for now, and then bring it back with the fix for #127, but then #127 should be high priority.

Many of those files whose linting is causing errors are either regular JS files or basically files that have been copy/pasted from their related frameworks' documentations, so I think linting those should either be low priority or completely unnecessary. Also, after fixing #127, this list will probably shrink considerably.

**Comment by alcipir** [comment]
Removed lint for now. 

@Gattaca1

**Review by Klakurka — CHANGES_REQUESTED** [review]
Still failing?

image

**Comment by alcipir** [comment]
Fixed!

**Review by Gattaca1 — APPROVED** [review]
Looks good to me

**Review by Klakurka — APPROVED** [review]

**Pull request merged**
