### PR TITLE
[Issue 145] refactor: validate addresses with `xecaddrjs`

### PR DESCRIPTION
**Pull request by chedieck**
**Description:**
Solves #145. Validation is now done by the `xecaddrjs` module. Now addresses without the chain prefix are accepted and their network is inferred, whenever possíble.

Remarks:
Since the functions in `xecaddrjs` do not differentiate the `bchreg` from the `bchtest` networks, an unprefixed test BCH address is interpreted as of the type `bchtest`. 

**Test Plan:**
All must be covered by the tests.

### CODE REVIEW

**Review by Gattaca1 — DISMISSED** [review]
Looks good to me

**Comment by Gattaca1** [comment]
Merge conflicts will need to be fixed before merging

**Review by Klakurka — DISMISSED** [review]

**Comment by Klakurka** [comment]
Tests are failing.

**Comment by chedieck** [comment]
> Tests are failing.

Fixed.

**Review by Klakurka — APPROVED** [review]

**Pull request merged**
