### PR TITLE
feat: add Apple and Facebook authentication

### PR DESCRIPTION
**Pull request by alcipir**
WARNING: Facebook it's a demo app, so only added testers may login.
Apple uses supertokens.io demo account, remember to change to one of ours in the future.

### CODE REVIEW

**Comment by alcipir** [comment]
New version of this PR deployed on: https://feat-facebook-auth.paybutton.io

**Comment by alcipir** [comment]
New version of this PR deployed on: https://feat-facebook-auth.paybutton.io

**Comment by Klakurka** [comment]
I assume this works although it doesn't let me test it due to my FB account not being in "development mode".

**Comment by alcipir** [comment]
New version of this PR deployed on: https://feat-facebook-auth.paybutton.io

**Comment by Klakurka** [comment]
I'm just going to accept this one.

**Pull request merged**
