### PR TITLE
[Issue #151] feat: Create dashboard API endpoint

### PR DESCRIPTION
**Pull request by chedieck**
Description:
Create an API endpoint to retrieve data to be used in the dashboard.

Test plan:
This is not implemented in the front end yet (will be done in a separate PR), but it can be tested by running:
 `curl http://localhost:3000/api/dashboard | jq`

Remarks:
- Dummy prices are being used instead of fetching the actual prices at the time of the transaction, which will be addressed in a future PR.

### CODE REVIEW

**Comment by johnkuney** [comment]
Overall looks good to me. Couple of things though
- Are the dummy prices just placeholder and price calls are coming in another PR? 
- I tried adding a new button but it didnt add the transactions for it...it changed the total button count, but the payments didnt change even though the address I added has some transactions in august. Although its also not showing transactions in the button view for the new button. Only for the dev buttons...is this expected and a work in progress?

**Comment by chedieck** [comment]
>    Are the dummy prices just placeholder and price calls are coming in another PR?

Yes, indeed. Forgot to mention in the description (now updated).
 
>   I tried adding a new button but it didnt add the transactions for it...it changed the total button count, but the payments didnt change even though the address I added has some transactions in august. Although its also not showing transactions in the button view for the new button. Only for the dev buttons...is this expected and a work in progress?

Right now, the transactions are only updated at login time. Try logging out and back again, see if they appear.

**Comment by johnkuney** [comment]
Thanks for the clarification. ah thats right we want to reflect the usd values at the time for each transaction

Logging out and in didnt change it for me... Can I test with any xec or bch address?

**Comment by chedieck** [comment]
> Logging out and in didnt change it for me... Can I test with any xec or bch address?

Aren't you missing the `.env` file with the XEC and BCH addresses?

**Comment by johnkuney** [comment]
oh shoot my bad. Yes it works when I config the .env. Is there a reason we havent added those to the codebase by default? Whenever I switch branches I have to remember to add them in

But yeah working better. Although I dont think its showing every payment from my test addresses. Theyre both ecash addresses and only have very small transaction amounts in them. Is there like a minimum amount that gets filtered out or something and doesnt register?

**Comment by Klakurka** [comment]
> oh shoot my bad. Yes it works when I config the .env. Is there a reason we havent added those to the codebase by default? Whenever I switch branches I have to remember to add them in
> 
> But yeah working better. Although I dont think its showing every payment from my test addresses. Theyre both ecash addresses and only have very small transaction amounts in them. Is there like a minimum amount that gets filtered out or something and doesnt register?

They aren't our APIs so not a good idea to put them in as defaults.

**Review by Klakurka — APPROVED** [review]

**Comment by chedieck** [comment]
> Although I dont think its showing every payment from my test addresses. Theyre both ecash addresses and only have very small transaction amounts in them. Is there like a minimum amount that gets filtered out or something and doesnt register?

I think this is the bug I have addressed on #220. Can you try it there?

**Comment by johnkuney** [comment]
Well actually the button view was showing all the transactions, but the payment count in the dashboard api was only going up by one. Either way, Im sure there will be gremlins to sort out, probably better to get this and #220 in, and get the dashboard frontend tied in, and then do more testing

**Review by johnkuney — APPROVED** [review]

**Pull request merged**
